Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

app:
  security:
    # Тестовый ключ только для демонстрации! В production использовать переменные окружения
    card-encryption-key: ${CARD_ENCRYPTION_KEY:dGVzdC1rZXktMjU2LWJpdC1mb3ItZGV2ZWxvcG1lbnQhISE=}
  jwt:
    # Base64 encoded 256-bit key для тестирования
    secret: ${JWT_SECRET:dGVzdEp3dFNlY3JldEtleUZvckJhbmtDYXJkc0FwcGxpY2F0aW9uMTIzNDU2Nzg5MA==}
    expiration: ${JWT_EXPIRATION:3600000}
