server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bankcards-api
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards}
    username: ${SPRING_DATASOURCE_USERNAME:bankcards_user}
    password: ${SPRING_DATASOURCE_PASSWORD:bankcards_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml

app:
  security:
    card-encryption-key: ${CARD_ENCRYPTION_KEY:dGVzdC1rZXktMjU2LWJpdC1mb3ItZGV2ZWxvcG1lbnQhISE=}
  jwt:
    secret: ${JWT_SECRET:dGVzdEp3dFNlY3JldEtleUZvckJhbmtDYXJkc0FwcGxpY2F0aW9uMTIzNDU2Nzg5MA==}
    expiration: ${JWT_EXPIRATION:3600000}
  front:
    origins:
      - http://allowed-origin.com
      - http://another-allowed-origin.com
    methods: 
      - POST
      - GET
      - PUT
      - DELETE
    headers: "*"
    allowedCredentials: true
    cache:
      maxAge: 3600

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



logging:
  level:
    '[com.example.bankcards]': DEBUG
    '[org.springframework.security]': INFO
    '[org.springframework.web]': INFO
    '[org.springdoc]': DEBUG
    '[org.springdoc.api]': TRACE